Repository InvictoProjects/streetly-shop, pull requests merged in 2024-01, with the labels that each got.

#9 SS-2 Provide authentication logic
  build.gradle.kts
  src/main/kotlin/com/invoctoprojects/streetlyshop/persistence/CustomerRepository.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/persistence/RefreshTokenRepository.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/persistence/domain/customer/Customer.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/persistence/domain/customer/Gender.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/persistence/domain/customer/RefreshToken.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/persistence/domain/customer/Role.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/persistence/impl/DefaultCustomerRepository.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/service/JWTService.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/service/LoginService.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/web/config/SecurityConfig.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/web/controller/AuthenticationController.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/web/controller/request/BasicLogicRequest.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/web/controller/response/ErrorResponse.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/web/controller/response/LoginResponse.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/web/exception/InvalidRefreshTokenException.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/web/exception/UserNotFoundException.kt
  src/main/kotlin/com/invoctoprojects/streetlyshop/web/filter/JWTAuthenticationFilter.kt
  src/main/resources/application.yml
  src/test/kotlin/com/invoctoprojects/streetlyshop/service/JWTServiceTest.kt
  src/test/kotlin/com/invoctoprojects/streetlyshop/service/LoginServiceTest.kt
  src/test/kotlin/com/invoctoprojects/streetlyshop/web/controller/AuthenticationControllerTest.kt
  src/test/kotlin/com/invoctoprojects/streetlyshop/web/filter/JWTAuthenticationFilterTest.kt
Labels: business logic, feature, security, testing

#12 SS-3: Implement customer components
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/CustomerRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/RefreshTokenRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/customer/Gender.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/customer/Customer.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/customer/Gender.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/customer/RefreshToken.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/customer/Role.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultCustomerRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/CustomerService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/JWTService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/facade/AuthenticationFacade.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/facade/DefaultAuthenticationFacade.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/config/SecurityConfig.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/CustomerController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/RegisterRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/UpdateCustomerDetailsRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/exception/AuthenticationRequiredException.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/exception/UserAlreadyRegisteredException.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/JWTServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/LoginServiceTest.kt
Labels: business logic, feature

#13 SS-6: Develop GitHub Actions Workflow
  .github/workflows/gradle.yaml
  .github/workflows/jib.yaml
  build.gradle.kts
  gradlew
Labels: build infrastructure, ci/cd, dependencies, testing

#27 SS-14: Implement Media Components
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/MediaRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultMediaRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/FileService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ImageService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/MediaService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/model/File.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/MediaController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/MediaDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/exception/MediaNotFoundException.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/validator/ImageValidator.kt
  src/main/resources/application.yml
  src/test/kotlin/com/invictoprojects/streetlyshop/service/FileServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ImageServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/MediaServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/MediaControllerTest.kt
  src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  src/test/resources/test/avatar/cat-avatar.jpeg
  src/test/resources/test/avatar/cat.jpeg
Labels: business logic, feature, testing

#28 SS-9: Implement Attribute definition Components
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/AttributeDefinitionRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/AttributeValueRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultAttributeDefinitionRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/AttributeDefinitionService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeDefinitionController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/AddAttributeDefinitionRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/UpdateAttributeNameRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/exception/AttributeNotFoundException.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/exception/AttributeValueNotFoundException.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/AttributeDefinitionServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeDefinitionControllerTest.kt
Labels: business logic, feature, testing

#29 SS-13: Implement Index Components
  src/main/kotlin/com/invictoprojects/streetlyshop/web/config/SecurityConfig.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/config/SwaggerConfig.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/IndexController.kt
Labels: business logic, feature, security, refactoring

#31 SS-3 Implement customer components
  src/main/kotlin/com/invictoprojects/streetlyshop/service/CustomerService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/config/SecurityConfig.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/CustomerController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/CustomerDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/AddFavoriteProductRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/RemoveFavoriteProductRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/response/ImageUploadResponse.kt
  src/main/resources/application.yml
  src/test/kotlin/com/invictoprojects/streetlyshop/service/CustomerServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/CustomerControllerTest.kt
Labels: business logic, feature, testing

#32 SS-8: Implement Variant Components
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/VariantRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/config/MongoConfig.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/config/MongoQueries.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/Currency.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/product/variant/Variant.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/product/variant/price/ExchangeRate.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/product/variant/price/Price.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultVariantRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ContentService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ExchangeRateService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ResourceReader.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/VariantService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/config/AzureBlobStorageConfig.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/VariantController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/PriceDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/StockDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/VariantDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/CreateVariantRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/UpdateStockRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/exception/StockException.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/VariantServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/VariantControllerTest.kt
Labels: business logic, feature, testing

#34 SS-18: Implement Review Components
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/ReviewRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ReviewService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/ReviewController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/ReviewDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/AddReviewRequest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ReviewServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/ReviewControllerTest.kt
Labels: business logic, feature, testing

#36 SS-10: Implement AttributeValue Components
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/product/attribute/AttributeValue.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultAttributeValueRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeValueController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/AttributeValueDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/validator/ValidAttributeFilter.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/AttributeValueServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeValueControllerTest.kt
Labels: business logic, feature, testing

#37 SS-18: Update README.md
  README.md
Labels: chore, documentation

#38 SS: 11 Implement attribute search components
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/ProductRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultProductRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/AttributeSearchService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/model/AttributeSearchAggregation.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/model/ProductSearchAggregation.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/config/SecurityConfig.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeSearchController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/AttributeSearchDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/AttributeSearchRequest.kt
  src/main/resources/aggregations/search/searchableAttributesPipeline.tmp
  src/test/kotlin/com/invictoprojects/streetlyshop/service/AttributeSearchServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeSearchControllerTest.kt
Labels: business logic, feature, testing

#39 SS-15: Implement notification components
  src/main/kotlin/com/invictoprojects/streetlyshop/service/TelegramService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/client/TelegramClient.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/NotificationController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/CallBackRequest.kt
  src/main/resources/application.yml
  src/test/kotlin/com/invictoprojects/streetlyshop/service/TelegramServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/NotificationControllerTest.kt
Labels: business logic, feature, testing

#42 SS-20: Add Detekt with Codacy
  detekt.yml
Labels: chore, ci/cd, refactoring

#40 SS-16: Implement Order Components
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/OrderRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/order/Order.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/order/OrderLine.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/order/OrderStatus.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultOrderRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/OrderService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/VariantService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/OrderController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/OrderDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/OrderLineDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/VariantInfoDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/CreateOrderRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/UpdateOrderStatusRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/exception/OrderNotFoundException.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/OrderServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/OrderControllerTest.kt
  src/test/resources/model/orderDTO.json
Labels: business logic, feature, testing

#45 SS-17: Implement ProductSearch Components
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/product/ProductSortingOrder.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ProductSearchService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ProductService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/VariantService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/config/SecurityConfig.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/GlobalExceptionHandler.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/ProductSearchController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/PaginatedProductSearchDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/ProductSearchRequest.kt
  src/main/resources/aggregations/getContent.tmp
  src/main/resources/aggregations/getProduct.tmp
  src/main/resources/aggregations/getVariant.tmp
  src/main/resources/aggregations/getVariantInfo.tmp
  src/main/resources/aggregations/search/facetStage.tmp
  src/main/resources/aggregations/search/matchGTStage.tmp
  src/main/resources/aggregations/search/matchInStage.tmp
  src/main/resources/aggregations/search/matchLTStage.tmp
  src/main/resources/aggregations/search/matchObjectIdStage.tmp
  src/main/resources/aggregations/search/projectStage.tmp
  src/main/resources/aggregations/search/searchPipeline.tmp
  src/main/resources/aggregations/search/sortStage.tmp
  src/main/resources/aggregations/search/textSearchStage.tmp
  src/main/resources/aggregations/variantPriceUpdate.tmp
  src/main/resources/aggregations/variantStockUpdate.tmp
  src/test/kotlin/com/invictoprojects/streetlyshop/service/AttributeServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ContentServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ProductSearchServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ProductServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/facade/DefaultAuthenticationFacadeTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/ContentControllerTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/ProductControllerTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/ProductSearchControllerTest.kt
Labels: business logic, feature, security, testing, refactoring

#44 SS-21: Refactor code
  README.md
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/Constants.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultAttributeDefinitionRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultAttributeValueRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultContentRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultMediaRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultOrderRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultProductRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultVariantRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/AttributeValueService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ContentService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ExchangeRateService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ImageService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/JWTService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/LoginService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ProductService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ReviewService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/client/TelegramClient.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/config/SecurityConfig.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/config/SwaggerConfig.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeDefinitionController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeSearchController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeValueController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/AuthenticationController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/CategoryController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/ContentController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/CustomerController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/ExchangeRateController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/MediaController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/ProductController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/ReviewController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/VariantController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/BasicLoginRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/CreateVariantRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/filter/JWTAuthenticationFilter.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/AttributeDefinitionServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/AttributeSearchServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/AttributeValueServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/CategoryServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/CustomerServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ExchangeRateServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/LoginServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/MediaServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/OrderServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ReviewServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/VariantServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeDefinitionControllerTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeSearchControllerTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeValueControllerTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/AuthenticationControllerTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/CategoryControllerTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/ExchangeRateControllerTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/NotificationControllerTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/ReviewControllerTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/filter/JWTAuthenticationFilterTest.kt
Labels: chore, refactoring

#46 SS-21: Refactor code
  build.gradle.kts
  src/main/kotlin/com/invictoprojects/streetlyshop/StreetlyShopApiApplication.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/order/Order.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/order/OrderLine.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/product/attribute/AttributeValue.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/product/content/Content.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/product/variant/price/ExchangeRate.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultAttributeValueRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultContentRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultOrderRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/impl/DefaultVariantRepository.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/service/MongoQueryService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/AttributeService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/OrderService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeValueController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/ContentController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/ExchangeRateController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/OrderController.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/AttributeDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/AttributeValueDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/ContentDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/ExchangeRateDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/OrderDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/OrderLineDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/VariantInfoDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/CreateContentRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/CreateOrderRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/UpdateAttributeValueNameRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/UpdateContentRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/UpdateExchangeRateRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/request/UpdateOrderStatusRequest.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/validator/ValidAttributeFilter.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/AttributeValueServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ContentServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ExchangeRateServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/OrderServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/AttributeValueControllerTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/ExchangeRateControllerTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/web/controller/OrderControllerTest.kt
Labels: chore, refactoring

#47 Release v1.0.0
  build.gradle.kts
Labels: release

#48 Refactor services and unit tests
  src/main/kotlin/com/invictoprojects/streetlyshop/persistence/domain/model/product/variant/price/ExchangeRate.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/AttributeDefinitionService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/AttributeSearchService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/AttributeService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/CategoryService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ContentService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/CustomerService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ExchangeRateService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/MediaService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/OrderService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ProductSearchService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ProductService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/ReviewService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/service/VariantService.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/util/CalcUtils.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/util/ConverterUtils.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/AttributeDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/AttributeDefinitionDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/AttributeSearchDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/AttributeValueDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/CategoryDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/ContentDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/CustomerDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/ExchangeRateDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/MediaDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/OrderDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/OrderLineDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/PaginatedProductSearchDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/PriceDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/ProductDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/ReviewDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/StockDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/VariantDTO.kt
  src/main/kotlin/com/invictoprojects/streetlyshop/web/controller/dto/VariantInfoDTO.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/AttributeDefinitionServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/AttributeSearchServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/AttributeServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/AttributeValueServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/CategoryServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ContentServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/CustomerServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ExchangeRateServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/FileServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/JWTServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/MediaServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/OrderServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ProductSearchServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ProductServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/ReviewServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/TelegramServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/service/VariantServiceTest.kt
  src/test/kotlin/com/invictoprojects/streetlyshop/util/MockHelper.kt
Labels: testing, refactoring
